export const getHeadCells = [
  {
    field: 'user',
    type: 'string',
    headerName: 'User',
    description: 'User',
    sortable: true,
    width: 200,
  },
  {
    field: 'department',
    type: 'string',
    headerName: 'Department',
    description: 'Department',
    sortable: true,
    flex: 1,
  },
  {
    field: 'location',
    type: 'string',
    headerName: 'Location',
    description: 'Location',
    sortable: true,
    flex: 1,
  },
  {
    field: 'designation',
    type: 'string',
    headerName: 'Designation',
    description: 'Designation',
    sortable: true,
    flex: 1,
  },
  {
    field: 'group',
    type: 'string',
    headerName: 'Group',
    description: 'Group',
    sortable: true,
    flex: 1,
  },
];
